### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by michal-bootcamp** [AgaMiasek/Batstropowo#1]
- [x] dorzucilem pare zmian na nowym branchu - zaciagnij zmiany do siebie lokalnie i domerguj mojego brancha do brancha master
- [x] sciagnij sobie obrazki, ktorych uzywasz i laduj je juz nie z internetu, tylko z katalogu np `images` (zmiane wykonaj na branchu master)

**Comment by AgaMiasek** [comment]
czy ewentualne pytania i komentarze mam umieszczać w Issues? czy gdzieś indziej?

**Comment by michal-bootcamp** [comment]
tak, pytania mozesz zadawac tutaj w danym issue lub stworzyc nowy, mozesz takze komentowac kazdy commit tutaj na githubie (albo dana linie kodu w commicie przez ten plus, ktory pokazywalem, lub pod samym commitem)

Tutaj poprosze Cie jeszcze o nastepujace rzeczy:
- [x] pliki dotyczace grunta usun, do zadania z gruntem zrob osobne repo
- [ ] plik `images/Thumbs.db` jest plikiem systemowym windowsa i nie powinien znalezc sie w repozytorium. Usun go, zakomituj jego usuniecie, a nastepnie utworz plik `.gitignore` i dodaj do niego wpis z nazwa tego pliku. Zakomituj i wypuszuj zmiany
